name: Deploy HTML to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy HTML
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          port: 22
          source: "index.html"
          target: "/var/www/html/"
          command: |
            sudo mv /var/www/html/index.html /var/www/html/index.html.bak
            sudo cp index.html /var/www/html/
